version: "3"
services:
    web:
        image: jupyter/web:sshspawner
        volumes:
            - ./config:/config
        ports:
            - 8000:8000
            - 8081:8081
    app1:
        image: jupyter/app:sshspawner
        volumes:
            - ./config:/config

    app2:
        image: jupyter/app:sshspawner
        volumes:
            - ./config:/config
