version: "3"
services:
  web:
    image: web-jupyterhub:latest
    volumes:
      - ./config:/config
    ports:
      - 8000:8000
      - 8081:8081
  app:
    image: app-notebooks:latest
    volumes:
      - ./config:/config
