version: "3"
services:
  web:
    user: root
    image: web-jupyterhub:latest
    container_name: web
    depends_on:
      - proxy
    environment:
      - CONFIGPROXY_AUTH_TOKEN=the-sign-pointed-this-way
      - INTERNAL_SSL_PATH=${SSL_VOLUME_CONTAINER}
    volumes:
      - ./config:/config
      - "ssl:${SSL_VOLUME_CONTAINER}:rw"
    restart: unless-stopped
  app:
    image: app-notebooks:latest
    container_name: app
    volumes:
      - ./config:/config
      - "ssl:${SSL_VOLUME_CONTAINER}:rw"
  proxy:
    user: root
    restart: always
    image: jupyterhub/configurable-http-proxy:latest
    container_name: proxy
    volumes:
      - "ssl:${SSL_VOLUME_CONTAINER}:ro"
    environment:
      - CONFIGPROXY_AUTH_TOKEN=the-sign-pointed-this-way
    ports:
      - 8000:8000
    command: >
       configurable-http-proxy
       --port 8000
       --api-ip 0.0.0.0
       --api-port 8001
       --error-target https://web:8081/hub/error
       --api-ssl-key ${SSL_VOLUME_CONTAINER}/proxy-api/proxy-api.key
       --api-ssl-cert ${SSL_VOLUME_CONTAINER}/proxy-api/proxy-api.crt
       --api-ssl-ca ${SSL_VOLUME_CONTAINER}/proxy-api-ca_trust.crt
       --api-ssl-request-cert
       --api-ssl-reject-unauthorized
       --client-ssl-key ${SSL_VOLUME_CONTAINER}/proxy-client/proxy-client.key
       --client-ssl-cert ${SSL_VOLUME_CONTAINER}/proxy-client/proxy-client.crt
       --client-ssl-ca ${SSL_VOLUME_CONTAINER}/proxy-client-ca_trust.crt
       --client-ssl-request-cert
       --client-ssl-reject-unauthorized

volumes:
  ssl:
    external:
      name: ${SSL_VOLUME_HOST}
